### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by guiwp** [Fannon/mwbot#1]
Could you please update the **README.md** pointing out how to set up the basic things with your library? 

e.g.: How to specify the `URI` of the MediaWiki project, how to securely specify and pass the username and password to the server, etc.

Thank you, keep up the good work ;)

**Comment by Fannon** [comment]
Hello guiwp,

yes, you're absolutely right, sorry for not having proper documentation yet.
I definately plan to document this library, but it might take a few weeks. Maybe I can update the readme, to at least include better and more complete examples until then.

Thanks for your interest!
Simon

**Comment by Fannon** [comment]
Hello @guiwp,

today I've written a lot of documentation, it should be pretty comprehensive now!
I'll also add some more advanced examples soon.

If you have feedback or further suggestions, just write it here.

Best,
Simon

**Comment by guiwp** [comment]
Hi @Fannon,

thank you very much, I appreciate your dedicated work on this project. I'll surely recommend your lib now =)

**Comment by Fannon** [comment]
Thanks!

2016-08-23 14:17 GMT+02:00 Guilherme V. Campos <notifications@github.com>:

**Comment by Fannon** [comment]
Ok, I've added the examples, too. 

I'm closing this issue. If something is unclear or still missing, just open a new one ;)
