### ISSUE TITLE
Add examples using async/await syntax

### ISSUE THREAD

**Issue by lucaswerkmeister** [Fannon/mwbot#14]
Thanks for creating this library! I used it to write a command-line version of the [namescript](https://github.com/lucaswerkmeister/namescript) user script and found it quite pleasant to work with :)

One thing that I think could be helpful: examples on how to use the library with `async`/`await` syntax instead of chaining `.then` calls. Since Bluebird promises (or any other Promises/A+ promises) are fully compatible with ES6 promises, this works out quite well, and I found it to be a very pleasant style of programming:

```js
async function main() {
    const bot = new MWBot({
        apiUrl: 'https://www.wikidata.org/w/api.php'
    });
    await bot.loginGetEditToken({
        username: …
        password: …
    });
    …
    for (const itemId of …) {
        await bot.request(…);
    }
}
main().catch(console.error);
```

Do you think it would be worth adding such examples? I could try to adapt some of the existing examples if you’re okay with it.

**Comment by Fannon** [comment]
Hello Lukas,

I'm glad this library works for you!

You are right. Since Node.js has proper async/await support, there's really no reason not to use the new syntax for it in almost all use cases.

I'll add your example to the documentation, thanks!

**Comment by Fannon** [comment]
https://github.com/Fannon/mwbot/commit/32dca91abec447f23d5596943e68c498a279d3e6#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by lucaswerkmeister** [comment]
Cool, thank you!
