### ISSUE TITLE
Get last edit information (for example last edit author)

### ISSUE THREAD

**Issue by DFelten** [Fannon/mwbot#16]
Is there already a possibility to get the information about the last edit of an article? I would like to change only pages where the last edit is also from the bot and not from an other user.

At the moment, at least I don't see any.

**Comment by gesinn-it** [comment]
Extension:Semantic_Extra_Special_Properties provides some extra meta information. This requires SMW. Usw mwbot's askQuery() then

https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/docs/configuration.md
