### ISSUE TITLE
user agent

### ISSUE THREAD

**Issue by hartman** [Fannon/mwbot#2]
You should probably add an option for user agent configuration, since it is part of the API and bot etiquette.

https://www.mediawiki.org/wiki/API:Etiquette#User-Agent_header
https://www.mediawiki.org/wiki/API:Main_page#Identifying_your_client
https://meta.wikimedia.org/wiki/User-Agent_policy

**Comment by Fannon** [comment]
Hello @hartman,

thanks for the hint! 
You can already set the user agent when constructing mwbot, but I've not explicitly documented that option and there is no good default.

So I'll go with the useragent `mwbot/1.0.3` by default and add an example to change the user agent.

Best,
Simon
