### ISSUE TITLE
Image uploads not working

### ISSUE THREAD

**Issue by siddharthvp** [Fannon/mwbot#31]
The `upload()` method doesn't seem to work. Trying 
```js
bot.upload('File:Example demo image', './path/example.png', 'test upload').then(console.log, console.log);
```
gives something like:
```
{
  upload: {
    result: 'Warning',
    warnings: { badfilename: 'Example_demo_image.png' },
    filekey: '17fs8hruecag.6ar5l2.26892.png',
    sessionkey: '17fs8hruecag.6ar5l2.26892.png'
  }
}
```
The image hasn't actually been uploaded. Changing the file name doesn't change anything. 

I had tried this out on [Test Wikipedia](https://test.wikipedia.org/), if that's relevant.

**Comment by gesinn-it** [comment]
We are using mwbot with MW 1.31 (LTS). It has not been tested with more current wikis. We might again work on mwbot when MW 1.35 becomes more relevant for us.

**Comment by gesinn-it** [comment]
works with current integration tests.
