### ISSUE TITLE
Error: Could not get edit token

### ISSUE THREAD

**Issue by machineghost** [Fannon/mwbot#6]
First off thanks for writing (what looks like) a really great library.  I was very excited to find it, particularly because it is promise-based and not callback-based.  However, I'm having some difficulty with it.

I copy/pasted the "Typical Example" source code, entered my a URL and authentication credentials, threw a couple logging lines in, and ran it.  When I did it appeared to login successfully, but then failed immediately because it was unable to grab an API token:

    node wiki_updater.js 
    [15:49:08] [S] [MWBOT] Login successful: me@http://wiki.somewikisomewhere.com
      { Error: Could not get edit token
    at request.then

Since there's no further information provided, I'm not sure where to go from here.  My wiki user has admin capabilities, so the only thing I can think of is that my media wiki installation (v1.28.0) is too old ... but since I don't see a minimum media wiki version listed I'm not certain that's even an issue.

Any help you could provide towards debugging this would be greatly appreciated, but just to be clear I'm ideally looking for a response like "go check ___ dummy"; I'm not trying to get you to debug my problems for me :)

**Comment by Fannon** [comment]
Hello,

thanks for the feedback!

MW 1.28 should be new enough for this to work.

I'm not sure what the problem might be. If you're using Promises, do you catch the error and print it back to the console? If you don't do this with Promises (in general) errors will get lost in the void ;)

Here's the code involved where it would go wrong:
https://github.com/Fannon/mwbot/blob/master/src/index.js#L343

If you want to go deepter into debugging, just go to your node_modules/mwbot and add console.logs or use a debugger if you've got it setup.

Does this help?

Best,
Simon

**Comment by machineghost** [comment]
> If you're using Promises, do you catch the error and print it back to the console? If you don't do this with Promises (in general) errors will get lost in the void ;)

I am (that's how I got the short message I posed):

    const bot = new MWBot();

    bot.loginGetEditToken(credentials).then(() => {
        return bot.edit('Test Page', '=Some more Wikitext=', 'Test Upload');
    }).then((response) => {
        console.log(resposne)
    }).catch((err) => {
        console.error(err)
    });

    ...

    node wiki_updater.js 
    [11:41:23] [S] [MWBOT] Login successful: me@http://wiki.somewikisomewhere.com
    { Error: Could not get edit token
        at request.then (/home/me/projects/project/node_modules/mwbot/src/index.js:361:31)

>Here's the code involved where it would go wrong:

>... just go to your node_modules/mwbot and ...

Normally I dread doing this sort of debugging, because a lot libraries use Babel nowadays and so then I have to figure out how to "compile" them to see my debugging changes.  Thankfully your library is just pure JS though so I'll take a crack at debugging and let you know what I find.

**Comment by machineghost** [comment]
Ok, I changed my code to log `err.response` and now see:

     response: { warnings: { main: [Object], query: [Object] } } } { warnings: 
       { main: { '*': 'Unrecognized parameter: \'type\'' },
         query: { '*': 'Unrecognized value for parameter \'meta\': tokens' } } }

**Comment by machineghost** [comment]
Actually, I'm going to close this ticket.  It seems the wiki I'm working with has a nonstandard API.  For instance, the documentation for it lists the only `meta` options as `allmessages`, `siteinfo`, `userinfo`.  `meta: 'tokens',` doesn't appear to even be a valid option, so I guess I'm going to have to build this thing at a lower level.

Thanks anyway for the help and good luck with the library.

**Comment by Fannon** [comment]
This is really unexpected, I didn't know that some Wikis have a nonstandard API. Maybe it's just the login process which has been changed? In any case, i fear that you have to handle this manually.

If thats any help to you, you could start by overwriting the loginGetEditToken function and see how it goes from there. But it wouldn't make much sense for this library to support nonstandard Wiki API's if they're not widespread. I was thinking about having a login function that first enquires information about the wiki and then decides on the correct login and API handling. But that's some work and currently I'm not working on MediaWiki related Projects anymore.

In any case, whish you good luck with your project!
